import React, { useCallback, useEffect, useMemo, useState } from "react";
import api from "../services/api";
import defaultAvatar from "../assets/default-avatar.png";
import { resolveMediaUrl } from "../utils/mediaUrl";
import { getTokenRole } from "../utils/auth";
import { useNavigate } from "react-router-dom";
import useUrlFilters from "../hooks/useUrlFilters";
import "./AdminPage.css";

const NAV = [
  ["overview", "grid", "Overview"], ["moderation", "shield", "Moderation"],
  ["users", "users", "Users"], ["posts", "post", "Posts"],
  ["jobs", "briefcase", "Job posts"], ["reports", "flag", "Post reports"],
  ["profileReports", "alert", "Profile reports"],
  ["staff", "users", "Staff"],
].filter(([key]) => key !== "staff" || getTokenRole(localStorage.getItem("token")) === "Admin");
const META = {
  overview: ["Overview", "Platform health and activity at a glance."],
  moderation: ["Moderation center", "Review risk signals and unresolved reports."],
  users: ["User management", "Review accounts, roles and access status."],
  posts: ["Post management", "Inspect publishing and AI moderation status."],
  jobs: ["Job post management", "Monitor live and restricted opportunities."],
  reports: ["Post reports", "Resolve community reports about content."],
  profileReports: ["Profile reports", "Prioritize reported accounts by risk score."],
};
const ADMIN_QUERY_DEFAULTS = { view: "overview", search: "", filter: "all" };
const PATHS = {
  grid: <><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,
  shield: <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/>,
  users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/></>,
  post: <><rect x="3" y="3" width="18" height="18" rx="3"/><path d="M7 8h10M7 12h10M7 16h6"/></>,
  briefcase: <><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18"/></>,
  flag: <><path d="M5 22V4"/><path d="M5 4h11l-1 5 3 3H5"/></>,
  alert: <><path d="M10.3 2.9 1.8 17a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 2.9a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></>,
  search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
  sun: <><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2"/></>,
  moon: <path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/>,
  monitor: <><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></>,
  refresh: <><path d="M20 7h-5V2"/><path d="M20 7a9 9 0 1 0 1 8"/></>,
  logout: <><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="m16 17 5-5-5-5M21 12H9"/></>,
  menu: <path d="M4 6h16M4 12h16M4 18h16"/>, close: <path d="m6 6 12 12M18 6 6 18"/>,
  arrow: <path d="m9 18 6-6-6-6"/>, trend: <path d="m3 17 6-6 4 4 8-8M15 7h6v6"/>,
  check: <path d="m5 12 4 4L19 6"/>, eye: <><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,
  lock: <><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,
  unlock: <><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 7.5-2"/></>,
};
const Icon = ({ name, size = 18 }) => <svg className="adm-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{PATHS[name] || PATHS.grid}</svg>;
const dataOf = (res) => Array.isArray(res?.data) ? res.data : Array.isArray(res?.data?.data) ? res.data.data : Array.isArray(res?.data?.Data) ? res.data.Data : res?.data?.data ?? res?.data?.Data ?? res?.data ?? null;
const v = (o, k, fallback = "") => o?.[k] ?? o?.[k[0].toUpperCase() + k.slice(1)] ?? fallback;
const n = (o, k) => Number(v(o, k, 0));
const img = (path) => resolveMediaUrl(path, defaultAvatar);
const date = (x) => x ? new Intl.DateTimeFormat("en", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(x)) : "—";
const clip = (x, len = 70) => String(x || "No content").length > len ? `${String(x).slice(0, len)}…` : String(x || "No content");

function Status({ tone = "neutral", children }) { return <span className={`adm-status ${tone}`}><i/>{children}</span>; }
function Metric({ icon, label, value, note, tone }) { return <article className="adm-metric"><span className={`adm-metric-icon ${tone}`}><Icon name={icon}/></span><div><small>{label}</small><strong>{Number(value || 0).toLocaleString()}</strong><p>{note}</p></div></article>; }
function Empty({ title = "Nothing found", text = "Try changing your filters." }) { return <div className="adm-empty"><span><Icon name="search"/></span><h3>{title}</h3><p>{text}</p></div>; }
function Person({ image, title, sub, wide = false }) { return <div className={`adm-person ${wide ? "wide" : ""}`}><img src={img(image)} alt=""/><span><strong>{title}</strong><small>{sub}</small></span></div>; }

function MonthlyChart({ items = [] }) {
  const list = items.slice(-12), max = Math.max(...list.map(x => n(x, "count")), 1);
  if (!list.length) return <Empty title="No registration data" text="Monthly activity will appear here."/>;
  return <div className="adm-chart">{list.map((x, i) => <div className="adm-chart-col" key={`${v(x,"year")}-${v(x,"month")}-${i}`}><b>{n(x,"count")}</b><div><i style={{height: `${Math.max(7, n(x,"count") / max * 100)}%`}}/></div><span>{new Date(n(x,"year"), n(x,"month") - 1).toLocaleString("en", {month:"short"})}</span></div>)}</div>;
}
function Donut({ dashboard }) {
  const a=n(dashboard,"totalJobSeekers"), b=n(dashboard,"totalEmployers"), pct=Math.round(a/Math.max(a+b,1)*100);
  return <div className="adm-donut-layout"><div className="adm-donut" style={{background:`conic-gradient(var(--brand) 0 ${pct}%, var(--violet) ${pct}% 100%)`}}><div><strong>{a+b}</strong><span>users</span></div></div><div className="adm-legend"><p><i className="blue"/>Job seekers <strong>{a}</strong></p><p><i className="violet"/>Employers <strong>{b}</strong></p></div></div>;
}
function ActionDialog({ action, busy, close, confirm }) {
  const [reason,setReason]=useState(""); if(!action) return null; const blocking=action.kind==="block";
  return <div className="adm-overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="adm-dialog"><button className="adm-icon-btn close" onClick={close}><Icon name="close"/></button><span className={`adm-dialog-icon ${blocking?"danger":"success"}`}><Icon name={blocking?"lock":"check"} size={24}/></span><h2>{action.title}</h2><p>{blocking?"This item will be hidden from regular users.":"The status will be updated immediately and recorded by the system."}</p>{blocking&&<label className="adm-field"><span>Reason <em>required for audit</em></span><textarea autoFocus rows="4" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Add a clear moderation reason…"/></label>}<footer><button className="adm-btn ghost" onClick={close}>Cancel</button><button className={`adm-btn ${blocking?"danger":"primary"}`} disabled={busy||(blocking&&!reason.trim())} onClick={()=>confirm(reason.trim())}>{busy?"Processing…":action.label}</button></footer></section></div>;
}
function Detail({ detail, loading, close }) {
  if(!detail) return null;
  const {type,item}=detail;
  if(loading) return <div className="adm-overlay"><section className="adm-modal adm-detail-loading">Loading complete details…</section></div>;
  const user=type==="user", job=type==="job", report=type==="report", profileReport=type==="profileReport";
  const reportPost=v(item,"post",{}), target=v(item,"reportedUser",{}), reporter=v(item,"reporter",{});
  const blocked=Boolean(v(user?item:profileReport?target:report?reportPost:item,"isBlocked",false));
  const title=report?`Post report #${v(item,"id")}`:profileReport?`Profile report #${v(item,"id")}`:user?v(item,"fullName","User"):job?v(item,"title","Job post"):v(item,"authorName","Post");
  const photo=report?v(v(reportPost,"author",{}),"profileImage"):profileReport?v(target,"profileImage"):user?v(item,"profileImage"):job?v(item,"companyLogo"):v(item,"authorProfileImage");
  const metrics=v(item,"metrics",{}), userPosts=v(item,"posts",[]), jobs=v(item,"jobs",[]), userReports=v(item,"profileReports",[]);
  return <div className="adm-overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="adm-modal adm-modal-large"><header><div><small>{report?"Post report":profileReport?"Profile report":user?"Account":job?"Job post":"Post"} details</small><h2>{title}</h2></div><button className="adm-icon-btn" onClick={close}><Icon name="close"/></button></header><div className="adm-modal-body">
    {(report||profileReport)&&<div className="adm-report-summary"><Status tone={v(item,"isReviewed",false)?"success":"warning"}>{v(item,"isReviewed",false)?"Reviewed":"Open"}</Status><time>Reported {date(v(item,"createdAt"))}</time><p><strong>Reason:</strong> {report?v(item,"reason","—"):v(item,"category","—")}</p>{profileReport&&<p><strong>Details:</strong> {v(item,"details","No additional details")}</p>}</div>}
    <div className="adm-detail-person"><Person image={photo} title={report?v(v(reportPost,"author",{}),"name","Unknown author"):profileReport?v(target,"fullName","Unknown user"):title} sub={report?`@${v(v(reportPost,"author",{}),"username","unknown")}`:profileReport?`@${v(target,"username","unknown")}`:user?`@${v(item,"username","unknown")}`:job?v(item,"companyName","Unknown company"):`@${v(item,"authorUsername","unknown")}`}/><Status tone={blocked?"danger":"success"}>{blocked?"Restricted":"Active"}</Status></div>
    <div className="adm-detail-grid"><div><span>Created</span><strong>{date(report?v(reportPost,"createdAt"):profileReport?v(target,"createdAt"):v(item,"createdAt"))}</strong></div>{user&&<><div><span>Account type</span><strong>{v(item,"userType","Unknown")}</strong></div><div><span>Email</span><strong>{v(item,"email","—")}</strong></div><div><span>Location</span><strong>{v(item,"location","—")}</strong></div></>}{job&&<><div><span>Location</span><strong>{v(item,"location","—")}</strong></div><div><span>Employment</span><strong>{v(item,"employmentType","—")}</strong></div></>}{report&&<><div><span>Post status</span><strong>{v(reportPost,"moderationStatus","—")}</strong></div><div><span>Reporter</span><strong>{v(reporter,"name","—")} · @{v(reporter,"username","—")}</strong></div></>}{profileReport&&<><div><span>Account type</span><strong>{v(target,"userType","—")}</strong></div><div><span>Reporter</span><strong>{v(reporter,"name","—")} · @{v(reporter,"username","—")}</strong></div></>}{!user&&!job&&!report&&!profileReport&&<><div><span>Moderation</span><strong>{v(item,"moderationStatus","Published")}</strong></div><div><span>AI risk</span><strong>{v(item,"aiModerationRiskLevel","Clear")}</strong></div></>}</div>
    {user&&<><div className="adm-metric-strip"><span><strong>{n(metrics,"postCount")}</strong>Posts</span><span><strong>{n(metrics,"jobCount")}</strong>Jobs</span><span><strong>{n(metrics,"reportCount")}</strong>Reports</span><span><strong>{n(metrics,"openReportCount")}</strong>Open reports</span></div>{v(item,"bio")&&<div className="adm-content-box"><span>About</span><p>{v(item,"bio")}</p></div>}</>}
    {(report||(!user&&!job&&!profileReport))&&<div className="adm-content-box"><span>Full post content</span><p>{report?v(reportPost,"content","No text content"):v(item,"content","No text content")}</p>{v(report?reportPost:item,"imageUrl")&&<img className="adm-detail-media" src={resolveMediaUrl(v(report?reportPost:item,"imageUrl"))} alt="Reported post"/>}</div>}
    {profileReport&&v(target,"bio")&&<div className="adm-content-box"><span>Reported profile bio</span><p>{v(target,"bio")}</p></div>}
    {job&&<div className="adm-content-box"><span>Description</span><p>{v(item,"description","No content")}</p></div>}
    {v(report?reportPost:profileReport?target:item,"blockReason")&&<div className="adm-reason"><Icon name="alert"/><div><strong>Restriction reason</strong><p>{v(report?reportPost:profileReport?target:item,"blockReason")}</p></div></div>}
    {user&&<div className="adm-related"><h3>User activity</h3><section><h4>Posts ({userPosts.length})</h4>{userPosts.length?userPosts.map(p=><article key={v(p,"id")}><div><strong>Post #{v(p,"id")}</strong><time>{date(v(p,"createdAt"))}</time></div><p>{v(p,"content","No text content")}</p><Status tone={v(p,"isBlocked",false)?"danger":"success"}>{v(p,"moderationStatus",v(p,"isBlocked",false)?"Restricted":"Published")}</Status></article>):<p className="adm-muted">No posts.</p>}</section>{jobs.length>0&&<section><h4>Job posts ({jobs.length})</h4>{jobs.map(j=><article key={v(j,"id")}><div><strong>{v(j,"title","Untitled")}</strong><time>{date(v(j,"createdAt"))}</time></div><p>{v(j,"description","No description")}</p></article>)}</section>}<section><h4>Profile reports ({userReports.length})</h4>{userReports.length?userReports.map(r=><article key={v(r,"id")}><div><strong>{v(r,"category","Report")}</strong><time>{date(v(r,"createdAt"))}</time></div><p>{v(r,"details","No additional details")}</p></article>):<p className="adm-muted">No profile reports.</p>}</section></div>}
  </div></section></div>;
}

export default function AdminPage(){
  const navigate=useNavigate();
  const [urlFilters,setUrlFilters]=useUrlFilters(ADMIN_QUERY_DEFAULTS);
  const role=getTokenRole(localStorage.getItem("token"))||"Staff";
  const tab=META[urlFilters.view]?urlFilters.view:"overview",query=urlFilters.search,filter=urlFilters.filter;
  const setQuery=value=>setUrlFilters({search:value});
  const setFilter=value=>setUrlFilters({filter:value});
  const [theme,setTheme]=useState(()=>localStorage.getItem("nexora-staff-theme")||"system"),[menu,setMenu]=useState(false);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[detailLoading,setDetailLoading]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState(""),[detail,setDetail]=useState(null),[action,setAction]=useState(null);
  const [dashboard,setDashboard]=useState({}),[users,setUsers]=useState([]),[posts,setPosts]=useState([]),[jobs,setJobs]=useState([]),[reports,setReports]=useState([]),[profileReports,setProfileReports]=useState([]);
  const activeTheme=theme==="system"?(window.matchMedia?.("(prefers-color-scheme: dark)").matches?"dark":"light"):theme;
  useEffect(()=>localStorage.setItem("nexora-staff-theme",theme),[theme]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(id)},[toast]);
  useEffect(()=>{document.body.style.overflow=detail||action||menu?"hidden":"";return()=>{document.body.style.overflow=""}},[detail,action,menu]);
  const loaders=useMemo(()=>({dashboard:async()=>setDashboard(dataOf(await api.get("/Admin/dashboard"))||{}),users:async()=>setUsers(dataOf(await api.get("/Admin/users"))||[]),posts:async()=>setPosts(dataOf(await api.get("/Admin/posts"))||[]),jobs:async()=>setJobs(dataOf(await api.get("/Admin/job-posts"))||[]),reports:async()=>setReports(dataOf(await api.get("/Admin/reports"))||[]),profileReports:async()=>setProfileReports(dataOf(await api.get("/Admin/profile-reports"))||[])}),[]);
  const loadAll=useCallback(async()=>{setLoading(true);setError("");try{await Promise.all(Object.values(loaders).map(x=>x()))}catch(e){setError(e.response?.data?.message||"Admin data could not be loaded. Check the API connection.")}finally{setLoading(false)}},[loaders]);
  useEffect(()=>{loadAll()},[loadAll]);
  const openDetail=async(type,item)=>{setDetail({type,item});const id=v(item,type==="profileReport"?"id":"id");const endpoint=type==="user"?`/Admin/users/${id}/details`:type==="report"?`/Admin/reports/${id}`:type==="profileReport"?`/Admin/profile-reports/${id}`:null;if(!endpoint)return;setDetailLoading(true);try{setDetail({type,item:dataOf(await api.get(endpoint))||item})}catch(e){setToast(e.response?.data?.message||"Complete details could not be loaded.")}finally{setDetailLoading(false)}};
  const ask=(kind,entity,id,name)=>setAction({kind,entity,id,title:kind==="block"?`Restrict ${name}`:kind==="review"?`Resolve ${name}`:kind==="approve"?`Approve ${name}`:`Restore ${name}`,label:kind==="block"?"Restrict":kind==="review"?"Mark reviewed":kind==="approve"?"Approve":"Restore"});
  const run=async(reason)=>{setBusy(true);try{const {kind,entity,id}=action;if(entity==="user")await api.post(`/Admin/users/${id}/${kind}`,kind==="block"?{reason}:undefined);if(entity==="post")await api.post(`/Admin/posts/${id}/${kind}`,kind==="block"?{reason}:undefined);if(entity==="job")await api.post(`/Admin/job-posts/${id}/${kind}`,kind==="block"?{reason}:undefined);if(entity==="report")await api.post(`/Admin/reports/${id}/review`);if(entity==="profile")await api.post(`/Admin/profile-reports/users/${id}/review`);const keys=entity==="user"?["users","profileReports","dashboard"]:entity==="post"?["posts","reports","dashboard"]:entity==="job"?["jobs","dashboard"]:entity==="report"?["reports","dashboard"]:["profileReports","dashboard"];await Promise.all(keys.map(k=>loaders[k]()));setAction(null);setDetail(null);setToast("Action completed successfully.")}catch(e){setToast(e.response?.data?.message||"Action could not be completed.")}finally{setBusy(false)}};
  const go=x=>{if(x==="staff")return navigate("/admin/staff");setUrlFilters({view:x,search:"",filter:"all"},{replace:false});setMenu(false)};
  const search=(items,fields)=>items.filter(x=>fields.some(k=>String(v(x,k,"")).toLowerCase().includes(query.toLowerCase())));
  const shownUsers=search(users,["fullName","username","email"]).filter(x=>filter==="all"||(filter==="blocked"?v(x,"isBlocked",false):String(v(x,"userType")).toLowerCase()===filter));
  const shownPosts=search(posts,["content","authorName","authorUsername"]).filter(x=>filter==="all"||(filter==="blocked"?v(x,"isBlocked",false):String(v(x,"moderationStatus")).toLowerCase()===filter));
  const shownJobs=search(jobs,["title","companyName","location"]).filter(x=>filter==="all"||(filter==="blocked"?v(x,"isBlocked",false):filter==="active"?v(x,"isActive",false)&&!v(x,"isBlocked",false):true));
  const shownReports=search(reports,["reason","reporterName","postOwnerName"]).filter(x=>filter==="all"||(filter==="open"?!v(x,"isReviewed",false):v(x,"isReviewed",false)));
  const shownProfiles=search(profileReports,["fullName","username","riskLevel"]).filter(x=>filter==="all"||String(v(x,"riskLevel")).toLowerCase()===filter);
  const filterOptions=tab==="users"?[["all","All"],["jobseeker","Job seekers"],["employer","Employers"],["blocked","Blocked"]]:tab==="posts"?[["all","All"],["pendingreview","Pending"],["published","Published"],["rejected","Rejected"],["blocked","Blocked"]]:tab==="jobs"?[["all","All"],["active","Active"],["blocked","Blocked"]]:tab==="reports"?[["all","All"],["open","Open"],["reviewed","Reviewed"]]:[["all","All"],["high","High risk"],["medium","Medium"],["low","Low"]];
  const Toolbar=({placeholder})=><div className="adm-toolbar"><label className="adm-search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label><div className="adm-pills">{filterOptions.map(([key,label])=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{label}</button>)}</div></div>;
  const Table=({heads,children,empty})=><div className="adm-table-wrap"><table className="adm-table"><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table>{!React.Children.count(children)&&<Empty text={empty}/>}</div>;

  const overview=<><section className="adm-metrics"><Metric icon="users" label="Total users" value={n(dashboard,"totalUsers")} note={`+${n(dashboard,"newUsersLast7Days")} in last 7 days`} tone="blue"/><Metric icon="post" label="Total posts" value={n(dashboard,"totalPosts")} note={`+${n(dashboard,"newPostsLast7Days")} in last 7 days`} tone="violet"/><Metric icon="briefcase" label="Active jobs" value={n(dashboard,"activeJobPosts")} note={`${n(dashboard,"totalJobPosts")} total listings`} tone="green"/><Metric icon="alert" label="Open reports" value={n(dashboard,"openReports")} note={`${n(dashboard,"totalReports")} received overall`} tone="orange"/></section><section className="adm-grid wide"><article className="adm-panel"><div className="adm-panel-head"><div><small>Growth</small><h2>New registrations</h2></div><Status tone="success"><Icon name="trend" size={14}/>12 months</Status></div><MonthlyChart items={v(dashboard,"monthlyRegistrations",[])}/></article><article className="adm-panel"><div className="adm-panel-head"><div><small>Audience</small><h2>User distribution</h2></div></div><Donut dashboard={dashboard}/></article></section><section className="adm-grid thirds"><Health title="Content health" items={[["green","Published",n(dashboard,"publishedPosts")],["orange","AI review",n(dashboard,"pendingAiReview")],["red","Rejected",n(dashboard,"rejectedPosts")]]}/><Health title="Current restrictions" items={[["red","Users",n(dashboard,"blockedUsers")],["red","Posts",n(dashboard,"blockedPosts")],["red","Jobs",n(dashboard,"blockedJobPosts")]]}/><article className="adm-panel adm-flow-panel"><div className="adm-panel-head"><div><small>Workflow</small><h2>Moderation flow</h2></div></div><div className="adm-flow"><span>AI scan</span><b/><span>Staff review</span><b/><span>Decision</span></div><button className="adm-link" onClick={()=>go("moderation")}>Open moderation center <Icon name="arrow" size={14}/></button></article></section></>;
  function Health({title,items}){return <article className="adm-panel"><div className="adm-panel-head"><div><small>Platform health</small><h2>{title}</h2></div></div><div className="adm-stat-lines">{items.map(([tone,label,value])=><p key={label}><span><i className={tone}/>{label}</span><strong>{value}</strong></p>)}</div></article>}
  const moderation=<><section className="adm-metrics three"><Metric icon="shield" label="AI review queue" value={n(dashboard,"pendingAiReview")} note="Awaiting a decision" tone="orange"/><Metric icon="flag" label="Open post reports" value={n(dashboard,"openPostReports")} note="Community signals" tone="violet"/><Metric icon="alert" label="Open profile reports" value={n(dashboard,"openProfileReports")} note="Account safety signals" tone="red"/></section><section className="adm-grid half"><Queue title="AI flagged posts" button={()=>go("posts")} empty="There are no AI flagged posts.">{posts.filter(p=>v(p,"isAiFlagged",false)||v(p,"moderationStatus")==="PendingReview").slice(0,5).map(p=><div key={v(p,"id")}><Person image={v(p,"authorProfileImage")} title={v(p,"authorName","Unknown")} sub={clip(v(p,"content"),48)}/><button className="adm-btn small" onClick={()=>openDetail("post",p)}>Review</button></div>)}</Queue><Queue title="Highest risk profiles" button={()=>go("profileReports")} empty="There are no unresolved profile reports.">{profileReports.filter(g=>n(g,"reportCount")>0).slice(0,5).map(g=><div key={v(g,"userId")}><Person image={v(g,"profileImage")} title={v(g,"fullName","Unknown")} sub={`${n(g,"reportCount")} unresolved reports`}/><Status tone={v(g,"riskLevel")==="High"?"danger":v(g,"riskLevel")==="Medium"?"warning":"success"}>{v(g,"riskLevel","Low")} · {n(g,"riskScore")}</Status></div>)}</Queue></section></>;
  function Queue({title,button,empty,children}){return <article className="adm-panel"><div className="adm-panel-head"><div><small>Priority queue</small><h2>{title}</h2></div><button className="adm-link" onClick={button}>View all <Icon name="arrow" size={14}/></button></div><div className="adm-queue">{children}{!React.Children.count(children)&&<Empty title="Queue is clear" text={empty}/>}</div></article>}
  const userRows=shownUsers.map(x=>{const id=v(x,"id"),blocked=Boolean(v(x,"isBlocked",false));return <tr key={id} className="adm-clickable-row" onClick={()=>navigate(`/admin/users/${id}`)}><td data-label="User"><Person image={v(x,"profileImage")} title={v(x,"fullName","Unnamed user")} sub={v(x,"email",`@${v(x,"username")}`)}/></td><td data-label="Type"><Status>{v(x,"userType","User")}</Status></td><td data-label="Joined">{date(v(x,"createdAt"))}</td><td data-label="Status"><Status tone={blocked?"danger":"success"}>{blocked?"Blocked":"Active"}</Status></td><td data-label="Actions"><Actions view={()=>navigate(`/admin/users/${id}`)} blocked={blocked} act={role==="Admin"?()=>ask(blocked?"unblock":"block","user",id,"user"):null}/></td></tr>});
  const postRows=shownPosts.map(x=>{const id=v(x,"id"),blocked=Boolean(v(x,"isBlocked",false)),status=v(x,"moderationStatus",blocked?"Rejected":"Published"),pending=status==="PendingReview";return <tr key={id}><td data-label="Post"><Person wide image={v(x,"authorProfileImage")} title={v(x,"authorName","Unknown")} sub={clip(v(x,"content"))}/></td><td data-label="Created">{date(v(x,"createdAt"))}</td><td data-label="Moderation"><Status tone={blocked||status==="Rejected"?"danger":pending?"warning":"success"}>{status}</Status></td><td data-label="AI signal"><Status tone={v(x,"isAiFlagged",false)?"warning":"neutral"}>{v(x,"aiModerationRiskLevel",v(x,"isAiFlagged",false)?"Flagged":"Clear")}</Status></td><td data-label="Actions"><Actions view={()=>setDetail({type:"post",item:x})} blocked={blocked} approve={pending?()=>ask("approve","post",id,"post"):null} act={()=>ask(blocked?"unblock":"block","post",id,"post")}/></td></tr>});
  const jobRows=shownJobs.map(x=>{const id=v(x,"id"),blocked=Boolean(v(x,"isBlocked",false)),active=v(x,"isActive",false)&&!blocked;return <tr key={id}><td data-label="Opportunity"><Person wide image={v(x,"companyLogo")} title={v(x,"title","Untitled role")} sub={v(x,"companyName","Unknown company")}/></td><td data-label="Location">{v(x,"location","—")}</td><td data-label="Created">{date(v(x,"createdAt"))}</td><td data-label="Status"><Status tone={blocked?"danger":active?"success":"neutral"}>{blocked?"Blocked":active?"Active":"Inactive"}</Status></td><td data-label="Actions"><Actions view={()=>setDetail({type:"job",item:x})} blocked={blocked} act={()=>ask(blocked?"unblock":"block","job",id,"job post")}/></td></tr>});
  function Actions({view,blocked,act,approve}){return <div className="adm-actions" onClick={event=>event.stopPropagation()}><button className="adm-icon-btn" title="View" onClick={view}><Icon name="eye"/></button>{approve&&<button className="adm-icon-btn success" title="Approve" onClick={approve}><Icon name="check"/></button>}{act&&<button className={`adm-icon-btn ${blocked?"success":"danger"}`} title={blocked?"Restore":"Restrict"} onClick={act}><Icon name={blocked?"unlock":"lock"}/></button>}</div>}
  const reportRows=shownReports.map(x=>{const reviewed=Boolean(v(x,"isReviewed",false));return <tr key={v(x,"id")}><td data-label="Report"><Person image={v(x,"reporterProfileImage")} title={v(x,"reason","No reason")} sub={`by ${v(x,"reporterName","Unknown")}`}/></td><td data-label="Reported post"><span className="adm-copy"><strong>{v(x,"postOwnerName","Unknown")}</strong><small>{clip(v(x,"postContent"),55)}</small></span></td><td data-label="Submitted">{date(v(x,"createdAt"))}</td><td data-label="Status"><Status tone={reviewed?"success":"warning"}>{reviewed?"Reviewed":"Open"}</Status></td><td data-label="Actions"><div className="adm-actions"><button className="adm-btn small" onClick={()=>openDetail("report",x)}>View details</button>{!reviewed&&<button className="adm-btn small" onClick={()=>ask("review","report",v(x,"id"),"report")}>Resolve</button>}</div></td></tr>});
  const profiles=<div className="adm-risk-grid">{shownProfiles.map(x=>{const id=v(x,"userId"),risk=v(x,"riskLevel","Low"),nReports=n(x,"reportCount"),items=v(x,"reports",[]);return <article className="adm-risk-card" key={id}><header><Person image={v(x,"profileImage")} title={v(x,"fullName","Unknown")} sub={`@${v(x,"username","unknown")}`}/><Status tone={risk==="High"?"danger":risk==="Medium"?"warning":"success"}>{risk}</Status></header><div className="adm-risk-score"><p><strong>{n(x,"riskScore")}</strong><span>/ 100 risk</span></p><div><i style={{width:`${Math.min(n(x,"riskScore"),100)}%`}}/></div></div><div className="adm-risk-facts"><span><strong>{nReports}</strong> open reports</span><span><strong>{n(x,"uniqueReporters")}</strong> reporters</span><span><strong>{n(x,"recentReports")}</strong> recent</span></div><div className="adm-report-items">{items.slice(0,3).map(r=><button key={v(r,"id")} onClick={()=>openDetail("profileReport",r)}><span><strong>{v(r,"category","Report")}</strong><small>{date(v(r,"createdAt"))} · {v(r,"reporterName","Unknown")}</small></span><Icon name="eye" size={16}/></button>)}</div><footer>{nReports>0&&<button className="adm-btn primary" onClick={()=>ask("review","profile",id,"profile reports")}>Mark all reviewed</button>}{role==="Admin"&&!v(x,"isBlocked",false)&&<button className="adm-btn outline-danger" onClick={()=>ask("block","user",id,"profile")}>Restrict account</button>}</footer></article>})}</div>;
  const List=({placeholder,heads,rows,empty,custom})=><section className="adm-panel adm-list"><Toolbar placeholder={placeholder}/>{custom}{!custom&&<Table heads={heads} empty={empty}>{rows}</Table>}{custom&&!React.Children.count(custom.props.children)&&<Empty text={empty}/>}</section>;
  const views={overview,moderation,users:<List placeholder="Search name, username or email…" heads={["User","Type","Joined","Status","Actions"]} rows={userRows} empty="No users match your search."/>,posts:<List placeholder="Search post or author…" heads={["Post","Created","Moderation","AI signal","Actions"]} rows={postRows} empty="No posts match your search."/>,jobs:<List placeholder="Search job, company or location…" heads={["Opportunity","Location","Created","Status","Actions"]} rows={jobRows} empty="No jobs match your search."/>,reports:<List placeholder="Search reason, reporter or owner…" heads={["Report","Reported post","Submitted","Status","Actions"]} rows={reportRows} empty="No reports match your filters."/>,profileReports:<List placeholder="Search profile or risk level…" custom={profiles} empty="No profiles match your filters."/>};
  const logout=()=>{["token","refreshToken","accessToken"].forEach(k=>localStorage.removeItem(k));window.location.href="/admin/login"};
  return <div className="admin-workspace" data-theme={activeTheme}>{menu&&<button className="adm-sidebar-shade" onClick={()=>setMenu(false)} aria-label="Close menu"/>}<aside className={`adm-sidebar ${menu?"open":""}`}><div className="adm-brand"><b>N</b><span><strong>Nexora</strong><small>Staff workspace</small></span><button className="adm-icon-btn adm-mobile-close" onClick={()=>setMenu(false)}><Icon name="close"/></button></div><nav>{NAV.map(([key,icon,label])=><button className={tab===key?"active":""} key={key} onClick={()=>go(key)}><Icon name={icon}/><span>{label}</span><i/></button>)}</nav><footer><div className="adm-role"><b>{role[0]}</b><span><strong>{role}</strong><small>Secure staff session</small></span></div><button className="adm-logout" onClick={logout}><Icon name="logout"/>Sign out</button></footer></aside><main className="adm-main"><header className="adm-topbar"><button className="adm-icon-btn adm-menu" onClick={()=>setMenu(true)}><Icon name="menu"/></button><div><small>Nexora administration</small><h1>{META[tab][0]}</h1><p>{META[tab][1]}</p></div><section><label className="adm-theme"><Icon name={theme==="dark"?"moon":theme==="light"?"sun":"monitor"}/><select value={theme} onChange={e=>setTheme(e.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><button className="adm-icon-btn" title="Refresh" onClick={loadAll}><Icon name="refresh"/></button></section></header><div className="adm-content">{error&&<div className="adm-error"><Icon name="alert"/><span>{error}</span><button onClick={loadAll}>Try again</button></div>}{loading?<div className="adm-loading"><i/><i/><i/><i/></div>:views[tab]}</div></main><Detail detail={detail} loading={detailLoading} close={()=>setDetail(null)}/><ActionDialog action={action} busy={busy} close={()=>!busy&&setAction(null)} confirm={run}/>{toast&&<div className="adm-toast"><Icon name="check"/>{toast}</div>}</div>;
}
