import React, { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../services/api";
import defaultAvatar from "../assets/default-avatar.png";
import { resolveMediaUrl } from "../utils/mediaUrl";
import "./AdminPage.css";
import "./AdminStaffPage.css";

const value=(item,key,fallback="")=>item?.[key]??item?.[key[0].toUpperCase()+key.slice(1)]??fallback;
const dataOf=(response)=>response?.data?.data??response?.data?.Data??response?.data;
const formatDate=(input)=>input?new Intl.DateTimeFormat("en",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(input)):"—";

export default function AdminStaffPage(){
  const navigate=useNavigate();
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[invite,setInvite]=useState(false),[form,setForm]=useState({fullName:"",userName:"",email:""}),[busy,setBusy]=useState(false),[toast,setToast]=useState(""),[target,setTarget]=useState(null),[reason,setReason]=useState("");
  const [theme,setTheme]=useState(()=>localStorage.getItem("nexora-staff-theme")||"system");
  const activeTheme=theme==="system"?(window.matchMedia?.("(prefers-color-scheme: dark)").matches?"dark":"light"):theme;
  const load=useCallback(async()=>{setLoading(true);setError("");try{const data=dataOf(await api.get("/Admin/staff"));setItems(Array.isArray(data)?data:[])}catch(e){setError(e.response?.data?.message||"Staff accounts could not be loaded.")}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);useEffect(()=>localStorage.setItem("nexora-staff-theme",theme),[theme]);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(timer)},[toast]);
  const submitInvite=async(event)=>{event.preventDefault();setBusy(true);try{await api.post("/Admin/staff/invite",form);setInvite(false);setForm({fullName:"",userName:"",email:""});await load();setToast("Moderator invitation sent.")}catch(e){setToast(e.response?.data?.message||"Invitation could not be sent.")}finally{setBusy(false)}};
  const changeStatus=async()=>{if(!target)return;const disabled=value(target,"isDisabled",false);if(!disabled&&!reason.trim())return;setBusy(true);try{await api.post(`/Admin/staff/${value(target,"id")}/${disabled?"enable":"disable"}`,disabled?undefined:{reason:reason.trim()});setTarget(null);setReason("");await load();setToast(disabled?"Moderator enabled.":"Moderator disabled.")}catch(e){setToast(e.response?.data?.message||"Status could not be changed.")}finally{setBusy(false)}};
  return <div className="admin-workspace ast-page" data-theme={activeTheme}><header className="ast-top"><button onClick={()=>navigate("/admin")}>← Admin</button><div><small>Nexora administration</small><h1>Staff management</h1><p>Invite and control Moderator accounts.</p></div><label>Theme <select value={theme} onChange={event=>setTheme(event.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></header><main className="ast-main"><section className="ast-heading"><div><span>ADMIN ONLY</span><h2>Moderators</h2><p>Moderators receive a secure password-creation link and use email 2FA on every staff login.</p></div><button onClick={()=>setInvite(true)}>+ Invite moderator</button></section>{error&&<div className="ast-error">{error} <button onClick={load}>Retry</button></div>}{loading?<div className="ast-state">Loading staff…</div>:items.length?<section className="ast-grid">{items.map(item=><article key={value(item,"id")}><header><img src={resolveMediaUrl(value(item,"profileImage"),defaultAvatar)} alt=""/><div><strong>{value(item,"fullName","Moderator")}</strong><span>@{value(item,"username","unknown")}</span></div><i className={value(item,"isDisabled",false)?"disabled":"active"}>{value(item,"isDisabled",false)?"Disabled":"Active"}</i></header><dl><div><dt>Email</dt><dd>{value(item,"email","—")}</dd></div><div><dt>Created</dt><dd>{formatDate(value(item,"createdAt"))}</dd></div><div><dt>Security</dt><dd>{value(item,"twoFactorEnabled",false)?"2FA enabled":"2FA unavailable"}</dd></div></dl>{value(item,"disableReason")&&<p className="ast-reason"><b>Reason:</b> {value(item,"disableReason")}</p>}<footer><button className={value(item,"isDisabled",false)?"enable":"disable"} onClick={()=>setTarget(item)}>{value(item,"isDisabled",false)?"Enable moderator":"Disable moderator"}</button></footer></article>)}</section>:<div className="ast-state"><strong>No moderators</strong><p>Invite the first moderator to begin.</p></div>}</main>
  {invite&&<div className="ast-overlay" onMouseDown={event=>event.target===event.currentTarget&&!busy&&setInvite(false)}><form className="ast-dialog" onSubmit={submitInvite}><button type="button" className="ast-close" onClick={()=>setInvite(false)}>×</button><span className="ast-mark">+</span><h2>Invite moderator</h2><p>The moderator creates their own password from the secure email link.</p><label>Full name<input autoFocus value={form.fullName} onChange={event=>setForm({...form,fullName:event.target.value})} required maxLength="100"/></label><label>Username<input value={form.userName} onChange={event=>setForm({...form,userName:event.target.value})} required minLength="3" maxLength="30"/></label><label>Email<input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} required/></label><footer><button type="button" onClick={()=>setInvite(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?"Sending…":"Send invitation"}</button></footer></form></div>}
  {target&&<div className="ast-overlay" onMouseDown={event=>event.target===event.currentTarget&&!busy&&setTarget(null)}><section className="ast-dialog"><button className="ast-close" onClick={()=>setTarget(null)}>×</button><span className={value(target,"isDisabled",false)?"ast-mark success":"ast-mark danger"}>!</span><h2>{value(target,"isDisabled",false)?"Enable moderator":"Disable moderator"}</h2><p>{value(target,"isDisabled",false)?"The moderator will be able to sign in again.":"Active staff sessions will be invalidated and login will be blocked."}</p>{!value(target,"isDisabled",false)&&<label>Reason<textarea rows="4" value={reason} onChange={event=>setReason(event.target.value)} required/></label>}<footer><button onClick={()=>setTarget(null)}>Cancel</button><button className={value(target,"isDisabled",false)?"primary":"danger"} disabled={busy||(!value(target,"isDisabled",false)&&!reason.trim())} onClick={changeStatus}>{busy?"Processing…":"Confirm"}</button></footer></section></div>}
  {toast&&<div className="ast-toast">{toast}</div>}</div>;
}
